export const questions = [
    { 'question': 'Türkiye\'nin başkenti neresidir?', 'options': ['Ankara', 'İstanbul'], 'answer': 'Ankara' },
    { 'question': 'Dünyanın en büyük okyanusu hangisidir?', 'options': ['Pasifik Okyanusu', 'Atlantik Okyanusu'], 'answer': 'Pasifik Okyanusu' },
    { 'question': 'Hangi gezegen Güneş Sistemi\'nde en yakındır?', 'options': ['Merkür', 'Venüs'], 'answer': 'Merkür' },
    { 'question': 'İstanbul Boğazı hangi iki denizi birbirine bağlar?', 'options': ['Karadeniz ve Marmara', 'Marmara ve Ege'], 'answer': 'Karadeniz ve Marmara' },
    { 'question': 'Bir haftada kaç gün vardır?', 'options': ['6', '7'], 'answer': '7' },
    { 'question': 'Dünyanın en yüksek dağı hangisidir?', 'options': ['Everest', 'K2'], 'answer': 'Everest' },
    { 'question': 'Hangisi Türkiye\'nin en büyük gölüdür?', 'options': ['Van Gölü', 'Tuz Gölü'], 'answer': 'Van Gölü' },
    { 'question': 'İlk Türk devletinin adı nedir?', 'options': ['Göktürkler', 'Selçuklular'], 'answer': 'Göktürkler' },
    { 'question': 'Aşağıdaki hayvanlardan hangisi uçabilir?', 'options': ['Kuşlar', 'Kediler'], 'answer': 'Kuşlar' },
    { 'question': 'Hangi gezegen kırmızı renkte görünür?', 'options': ['Mars', 'Venüs'], 'answer': 'Mars' },
    { 'question': 'Bir üçgenin iç açıları toplamı kaç derecedir?', 'options': ['180', '90'], 'answer': '180' },
    { 'question': 'En büyük kara hayvanı hangisidir?', 'options': ['Fil', 'Aslan'], 'answer': 'Fil' },
    { 'question': 'Hangi renk Türk bayrağında bulunmaz?', 'options': ['Yeşil', 'Kırmızı'], 'answer': 'Yeşil' },
    { 'question': 'İlk Türk devletini kim kurmuştur?', 'options': ['Kutluk Kağan', 'Osman Gazi'], 'answer': 'Kutluk Kağan' },
    { 'question': 'Hangi gezegenin halkaları vardır?', 'options': ['Satürn', 'Venüs'], 'answer': 'Satürn' },
    { 'question': 'İstanbul Boğazı hangi iki kıta arasında yer alır?', 'options': ['Asya ve Avrupa', 'Asya ve Afrika'], 'answer': 'Asya ve Avrupa' },
    { 'question': 'Dünyadaki en büyük çöl hangisidir?', 'options': ['Sahara Çölü', 'Gobi Çölü'], 'answer': 'Sahara Çölü' },
    { 'question': 'Dünya\'nın en büyük hayvanı nedir?', 'options': ['Mavi Balina', 'Fil'], 'answer': 'Mavi Balina' },
    { 'question': 'Hangi gezegenin yüzeyi çok sıcak ve bulutlarla kaplıdır?', 'options': ['Venüs', 'Mars'], 'answer': 'Venüs' },
    { 'question': 'Hangi hayvan en hızlı koşar?', 'options': ['Çita', 'Zebra'], 'answer': 'Çita' },
    { 'question': 'Dünyanın en büyük ormanı hangisidir?', 'options': ['Amazon Ormanı', 'Sibirya Ormanı'], 'answer': 'Amazon Ormanı' },
    { 'question': 'Türkiye\'deki en yüksek dağ hangisidir?', 'options': ['Ararat Dağı', 'Erciyes Dağı'], 'answer': 'Ararat Dağı' },
    { 'question': 'İlk yapay uydu hangisidir?', 'options': ['Sputnik 1', 'Apollo 11'], 'answer': 'Sputnik 1' },
    { 'question': 'Bir yıl kaç gündür?', 'options': ['365', '366'], 'answer': '365' },
    { 'question': 'Hangi gezegen Güneş Sistemi\'nde en büyük gezegendir?', 'options': ['Jüpiter', 'Satürn'], 'answer': 'Jüpiter' },
    { 'question': 'Dünyada en çok konuşulan dil hangisidir?', 'options': ['Çince', 'İngilizce'], 'answer': 'Çince' },
    { 'question': 'Hangisi bir elektronik cihaz değildir?', 'options': ['Kalem', 'Telefon'], 'answer': 'Kalem' },
    { 'question': 'Türkiye\'deki en uzun nehir hangisidir?', 'options': ['Kızılırmak', 'Fırat'], 'answer': 'Kızılırmak' },
    { 'question': 'Dünyadaki en büyük hayvan hangisidir?', 'options': ['Balina', 'Fil'], 'answer': 'Balina' },
    { 'question': 'Hangi gezegen Güneş Sistemi\'nde en hızlı hareket eden gezegendir?', 'options': ['Merkür', 'Venüs'], 'answer': 'Merkür' },
    { 'question': 'Hangisi bir meyve değildir?', 'options': ['Havuç', 'Biber'], 'answer': 'Havuç' },
    { 'question': 'Hangisi en büyük gezegendir?', 'options': ['Jüpiter', 'Satürn'], 'answer': 'Jüpiter' },
    { 'question': 'İlk Türk devletinin kurucusu kimdir?', 'options': ['Kutluk Kağan', 'Osman Gazi'], 'answer': 'Kutluk Kağan' },
    { 'question': 'Hangi gezegenin atmosferi çok kalındır?', 'options': ['Venüs', 'Mars'], 'answer': 'Venüs' },
    { 'question': 'Türk bayrağındaki ay ve yıldız neyi simgeler?', 'options': ['Birliği ve bağımsızlığı', 'Huzuru ve gücü'], 'answer': 'Birliği ve bağımsızlığı' },
    { 'question': 'Türkiye\'nin en büyük gölü hangisidir?', 'options': ['Van Gölü', 'Tuz Gölü'], 'answer': 'Van Gölü' },
    { 'question': 'Aşağıdaki gezegenlerden hangisi en sıcak olanıdır?', 'options': ['Venüs', 'Mars'], 'answer': 'Venüs' },
    { 'question': 'İstanbul hangi iki kıta üzerinde yer alır?', 'options': ['Asya ve Avrupa', 'Avrupa ve Asya'], 'answer': 'Asya ve Avrupa' },
    { 'question': 'En büyük kara hayvanı hangisidir?', 'options': ['Fil', 'Zürafa'], 'answer': 'Fil' },
    { 'question': 'Hangi hayvan en hızlı koşar?', 'options': ['Çita', 'Kanguru'], 'answer': 'Çita' },
    { 'question': 'Hangisi bir fiziksel olay değildir?', 'options': ['Duygu', 'Yağmur'], 'answer': 'Duygu' },
    { 'question': 'Hangisi, ışığın hızıyla ilgili bir deneydir?', 'options': ['Michelson-Morley Deneyi', 'Einstein\'ın Deneyi'], 'answer': 'Michelson-Morley Deneyi' },
    { 'question': 'Dünyadaki en hızlı hayvan hangisidir?', 'options': ['Çita', 'Aslan'], 'answer': 'Çita' },
    { 'question': 'Hangi gezegen Güneş Sistemi\'nde en büyüğüdür?', 'options': ['Jüpiter', 'Satürn'], 'answer': 'Jüpiter' },
    { 'question': 'Hangisi elektronik cihazdır?', 'options': ['Telefon', 'Kitap'], 'answer': 'Telefon' }
  ];  